#!/bin/bash
outfile="../reload.xml"
echo "<code>" > "$outfile"
echo "<![CDATA[" >> "$outfile"
cat ai/AIDriveStrategyCourse.lua >> "$outfile"
cat ai/AIDriveStrategyFieldWorkCourse.lua >> "$outfile"
cat ai/AIDriveStrategyCombineCourse.lua >> "$outfile"
cat ai/AIDriveStrategyPlowCourse.lua >> "$outfile"
cat ai/AIDriveStrategyDriveToFieldWorkStart.lua >> "$outfile"
cat ai/AIDriveStrategyVineFieldWorkCourse.lua >> "$outfile"
cat ai/AIDriveStrategyFindBales.lua >> "$outfile"
cat ai/AIDriveStrategyUnloadCombine.lua >> "$outfile"
echo "]]>" >> "$outfile"
echo "</code>" >> "$outfile"
